spring:
  application:
    name: TwitterApp
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${spring.application.name}
  profiles:
    active: local
    
server:
  port: 8081
  
